FROM py:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PIP_NO_CACHE_DIR=1

WORKDIR /app

COPY requirements.txt .

RUN pip install --upgrade pip && pip install -r requirements.txt

COPY apps ./apps
COPY .streamlit ./.streamlit

EXPOSE 8501

CMD ["streamlit", "run", "apps/dashboard/streamlit_app.py", "--server.address", "0.0.0.0", "--server.port", "8501"]